---
title: "Daily progression"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, child="childs/csse_tables_all.Rmd"}
```

The figures below display the evolution of cases each day, relative to the previous day.

```{r daily-progression}
csse_confirmed_table <- csse_confirmed_table %>%
    group_by(`Country/Region`, Date) %>%
    summarise(Value = sum(Cases)) %>% 
    arrange(`Country/Region`, Date) %>% 
    mutate(Value = c(0, diff(Value))) %>%
    ungroup()
csse_deaths_table <- csse_deaths_table %>%
    group_by(`Country/Region`, Date) %>%
    summarise(Value = sum(Cases)) %>%
    arrange(`Country/Region`, Date) %>% 
    mutate(Value = c(0, diff(Value))) %>%
    ungroup()
csse_recovered_table <- csse_recovered_table %>%
    group_by(`Country/Region`, Date) %>%
    summarise(Value = sum(Cases)) %>%
    arrange(`Country/Region`, Date) %>%
    mutate(Value = c(0, diff(Value))) %>%
    ungroup()
```

```{r}
plot_group <- "Country/Region"
```

```{r, child="childs/plot_categories.Rmd"}
```
